rootUrl: http://localhost:8000/
gridUrl: http://ondemand.saucelabs.com/wd/hub
browsers:
  - {name: chrome, version: 33}
  - {name: opera, version: 12}
  - {name: firefox, version: 29}
  - {name: internet explorer, version: 9}
capabilities:
  record-screenshots: false
  record-video: false
  command-timeout: 5
  idle-timeout: 15
