language: node_js

node_js:
  - "0.10"

env:
  global:
    - secure: "oW2wxELTij/SZo+FV5jWcG3VsEqT1/LvKBbbLu9Flze8OzOpH1xDkR/hBJn+sMsGqDHrrxao1njr6yGosMTunss0OTUvDIWvhepH81ZHseaDtJigI95YOpFIZanHtc0zq7XdM5ZhiztmcQNQcUuOYK8x5wM7CBW+dumrEahkfbU="
    - secure: "rfQksY2zvIDbaz+ZPUtVLhpq8iJk+9HHyhlz37gJjnCboFwQi2rrZIXkoatl3XqFRu5f8uBsBgh8WV3j116YzhKbXsGLwdLIKogGQgI7jR3jaDiXhG/eh5wwWqvUixrCK9A3xs2W3tXTa/7vpgxrxruMx37+GdTuDE4bQaajTG8="

addons:
  sauce_connect: true

before_script:
  - npm run deps && npm run build
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y graphicsmagick
  - npm install http-server
  - node_modules/.bin/http-server -s -p 8000 &
  - |
      echo "  tunnel-identifier: '${TRAVIS_JOB_NUMBER}'" >> .gemini.yml
      echo "  build: '${TRAVIS_BUILD_NUMBER}'" >> .gemini.yml
      echo "  tags:" >> .gemini.yml
      echo "  - CI" >> .gemini.yml
      cat .gemini.yml
